### ISSUE TITLE
Github Authentication

### ISSUE THREAD

**Issue by kamoltat** [VallariAg/teuthology-api#25]
**Current progress:**

In `teuthology-api` you can authenticate with github (you have to be a member of ceph organization) which gives you permission to use `teuthology-suite` and `teuthology-kill`.

**Todo**

- [ ] 1. pulpito-ng should have a login/logout button displaying username (or icon) on top right corner.
- [ ] 2. Basically login button calls the `login` `logout` endpoint in teuthology-api.
- [ ] 3. Incorporate some sort of unit-test to this.
